/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import model.Car;
import model.CarHistory;

/**
 *
 * @author somnathsolaskar
 */
public class CreatePanel extends javax.swing.JPanel {

    /**
     * Creates new form createPanel
     */
    CarHistory history;
    public CreatePanel(CarHistory history) {
        initComponents();
        this.history = history;
        combo.removeAllItems();
        combo.addItem("5");
        combo.addItem("7");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        name1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        manufacturer1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        serial1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        city1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        model1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        manufacturingYear1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        company1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        available1 = new javax.swing.JCheckBox();
        btnSubmit = new javax.swing.JButton();
        maintenanceValid = new javax.swing.JCheckBox();
        combo = new javax.swing.JComboBox<>();

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("CREATE CAR RECORD");

        jLabel1.setText("Car Name");

        jLabel2.setText("Manufacturer");

        jLabel3.setText("Serial Number");

        jLabel4.setText("Location");

        jLabel5.setText("Model Number");

        jLabel6.setText("Manufacturing Year");

        jLabel8.setText("Travel Company");

        jLabel9.setText("Seats");

        available1.setText("Available");
        available1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                available1ActionPerformed(evt);
            }
        });

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        maintenanceValid.setText("Maintenance Validity");
        maintenanceValid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maintenanceValidActionPerformed(evt);
            }
        });

        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(303, 303, 303)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSubmit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(available1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maintenanceValid)
                    .addComponent(name1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manufacturer1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serial1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(city1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(model1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manufacturingYear1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(company1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(name1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(manufacturer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(serial1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(city1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(model1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(manufacturingYear1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(company1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(maintenanceValid)
                .addGap(18, 18, 18)
                .addComponent(available1)
                .addGap(3, 3, 3)
                .addComponent(btnSubmit)
                .addContainerGap(122, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void available1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_available1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_available1ActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        
        int res = validateInput();
        if(res == 0){
        String name = name1.getText();
        String manufacturer = manufacturer1.getText();
        String serial = serial1.getText();
        String city = city1.getText();
        String model = model1.getText();
        int manYear = Integer.parseInt(manufacturingYear1.getText());
        String company = company1.getText();
        int seats = Integer.parseInt(combo.getSelectedItem().toString());
        boolean mainValid ;
        if(maintenanceValid.isSelected()){
             mainValid = true;
        }
        else{
            mainValid = false;
        }
        boolean availability ;
        if(available1.isSelected()){
             availability = true;
        }
        else{
            availability = false;
        }
        
        Car car = history.addCar();
        car.setCarName(name);
        car.setManufacturer(manufacturer);
        car.setNumberPlate(serial);
        car.setCity(city);
        car.setModelNumber(model);
        car.setManufacturingYear(manYear);
        car.setMaintenanceExpiry(mainValid);
        car.setCompany(company);
        car.setSeats(seats);
        car.setAvailability(availability);
        car.setDateTime("");
        
        JOptionPane.showMessageDialog(this,"New Car Record Added");
        
        name1.setText("");
        manufacturer1.setText("");
        serial1.setText("");
        city1.setText("");
        model1.setText("");
        manufacturingYear1.setText("");
        maintenanceValid.setSelected(false);
        company1.setText("");
        available1.setSelected(false);
        combo.setSelectedItem("5");
        }
        
        
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void maintenanceValidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maintenanceValidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maintenanceValidActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox available1;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JTextField city1;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JTextField company1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JCheckBox maintenanceValid;
    private javax.swing.JTextField manufacturer1;
    private javax.swing.JTextField manufacturingYear1;
    private javax.swing.JTextField model1;
    private javax.swing.JTextField name1;
    private javax.swing.JTextField serial1;
    // End of variables declaration//GEN-END:variables

  public int validateInput(){
        int flag = 0;
         if(name1.getText().equals("")){
             flag = 1;
            JOptionPane.showMessageDialog(null,"Name is required");
        } 
         boolean isDuplicate = false;
         for(Car car: history.getHistory()){
            if(serial1.getText().equals(car.getNumberPlate())){
                isDuplicate = true;
        }
        }
          if(serial1.getText().equals("")){
            flag = 1;
              JOptionPane.showMessageDialog(null,"Serial Number is required");
        } 
          if(isDuplicate == true){
            flag = 1;
              JOptionPane.showMessageDialog(null,"Please enter a unique serial number", "Error", JOptionPane.ERROR_MESSAGE);
        } 
          if (manufacturer1.getText().equals("")) {
              flag = 1;
              JOptionPane.showMessageDialog(null, "Manufacturer is required");
            }
          boolean valid = Pattern.matches("(?:(?:19|20)[0-9]{2})$",manufacturingYear1.getText());//1900-2099 //2030
          boolean check = true;
          if(valid){
          int date = Integer.parseInt(manufacturingYear1.getText());
          if(date>2021 || date<2007){
              check = false;
          }
          }
          else{
          check = true;
          }
          if (manufacturingYear1.getText().equals("") || check == false) {
              flag = 1;
              JOptionPane.showMessageDialog(null, "Please enter a valid Manufacturing year from 2007 - 2021", "Error", JOptionPane.ERROR_MESSAGE);
            }
            if(company1.getText().equals("")){
                flag =1;
            JOptionPane.showMessageDialog(null,"Company name is required");
        } 
            if(city1.getText().equals("")){
                flag =1;
            JOptionPane.showMessageDialog(null,"City is required");
        } 
            if(model1.getText().equals("")){
                flag =1;
            JOptionPane.showMessageDialog(null,"Please enter a valid Model number");
        } 
  
            return flag;
    }
}
