/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.text.ParseException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat; 
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.Collections;
import java.util.Locale;

import model.Car;
import model.CarHistory;

/**
 *
 * @author somnathsolaskar
 */
public class ViewPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPanel
     */
    CarHistory history;
    private Car car;
    public ViewPanel(CarHistory history) {
        initComponents();
        this.history = history;
        populateTable();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCar = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        name2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        manufacturer2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        serial2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        city2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        model2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        manufacturingYear2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        company2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        seats2 = new javax.swing.JTextField();
        availability2 = new javax.swing.JCheckBox();
        btnSave = new javax.swing.JButton();
        maintenanceValid = new javax.swing.JCheckBox();
        updateStatus = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        updateRefresh = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("VIEW CAR RECORDS");

        tblCar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Car Name", "Manufacturer", "Location", "Serial Number", "Available", "Last Update"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCar);

        jButton1.setText("View");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jLabel1.setText("Car Name");

        jLabel2.setText("Manufacturer");

        jLabel3.setText("Serial Number/ Number Plate");

        jLabel4.setText("Location");

        jLabel5.setText("Model Number");

        jLabel6.setText("Manufacturing Year");

        jLabel8.setText("Travel Company");

        jLabel9.setText("Seats");

        availability2.setText("Availability");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        maintenanceValid.setText("Maintenance Validity");

        jButton2.setText("Catalog Last Updated on");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(108, 108, 108)
                                .addComponent(updateRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addGap(57, 57, 57)
                                .addComponent(btnDelete)
                                .addGap(17, 17, 17))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(name2)
                                    .addComponent(manufacturer2)
                                    .addComponent(serial2)
                                    .addComponent(city2)
                                    .addComponent(seats2, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(model2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(manufacturingYear2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(company2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(maintenanceValid)
                                    .addComponent(availability2))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(257, 257, 257)
                .addComponent(btnUpdate)
                .addGap(39, 39, 39)
                .addComponent(btnSave)
                .addGap(72, 72, 72)
                .addComponent(updateStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnDelete)
                    .addComponent(jButton2)
                    .addComponent(updateRefresh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(name2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(model2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(manufacturer2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(manufacturingYear2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(serial2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(company2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(city2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(maintenanceValid)))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(seats2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(availability2))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(updateStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate))
                .addGap(222, 222, 222))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selected = tblCar.getSelectedRow();
        if(selected < 0){
        JOptionPane.showMessageDialog(this,"Please selected the row to be deleted");
        return;
        }
        DefaultTableModel model = (DefaultTableModel) tblCar.getModel();
        Car selectedCar = (Car) model.getValueAt(selected,0);
        history.deleteCar(selectedCar);
         JOptionPane.showMessageDialog(this,"Car Record Deleted");
         populateTable();
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         int selected = tblCar.getSelectedRow();
        if(selected < 0){
        JOptionPane.showMessageDialog(this,"Please selected the row to be viewed");
        return;
        }
        DefaultTableModel model = (DefaultTableModel) tblCar.getModel();
        Car selectedCar = (Car) model.getValueAt(selected,0);
        name2.setText(selectedCar.getCarName());
        manufacturer2.setText(selectedCar.getManufacturer());
        serial2.setText(selectedCar.getNumberPlate());
        city2.setText(selectedCar.getCity());
        model2.setText(selectedCar.getModelNumber());
        manufacturingYear2.setText(String.valueOf(selectedCar.getManufacturingYear()));
        maintenanceValid.setSelected(selectedCar.isMaintenanceExpiry());
        company2.setText(selectedCar.getCompany());
        seats2.setText(String.valueOf(selectedCar.getSeats()));
        availability2.setSelected(selectedCar.isAvailability());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
    
      
         int selected = tblCar.getSelectedRow();
        if(selected < 0){
        JOptionPane.showMessageDialog(this,"Please selected the row to be viewed");
        return;
        }
        DefaultTableModel model = (DefaultTableModel) tblCar.getModel();
        Car selectedCar = (Car) model.getValueAt(selected,0);
        selectedCar.setCity(city2.getText());
        boolean mainValid ;
        if(maintenanceValid.isSelected()){
             mainValid = true;
        }
        else{
            mainValid = false;
        }
        selectedCar.setCompany(company2.getText());
        boolean availability ;
        if(availability2.isSelected()){
             availability = true;
        }
        else{
            availability = false;
        }
        selectedCar.setAvailability(availability);
       updateStatus.setText("");//date
       Date date = new Date();  
       SimpleDateFormat formatter = new SimpleDateFormat("MM-dd-yyyy hh:mm:ss a");   
       updateStatus.setText("Last Updated on : " + date);
       selectedCar.setDateT(date);
        refreshTable();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         ArrayList<Date> dateList = new ArrayList<Date>();
         SimpleDateFormat formatter = new SimpleDateFormat("MM-dd-yyyy hh:mm:ss a");
        for (Car car: history.getHistory()) {
            
            if(car.getDateT() != null){
            dateList.add(car.getDateT());
            }
        }
    if(dateList.size()>0){
       String maxDate = formatter.format(Collections.max(dateList));
        updateRefresh.setText(maxDate);
    }
    else{
        updateRefresh.setText("Never Updated");
    }
      
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        name2.setEditable(false);
        manufacturer2.setEditable(false);
        serial2.setEditable(false);
        manufacturingYear2.setEditable(false);
        seats2.setEditable(false);
        model2.setEditable(false);
        city2.setEditable(true);
        company2.setEditable(true);
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox availability2;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JTextField city2;
    private javax.swing.JTextField company2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JCheckBox maintenanceValid;
    private javax.swing.JTextField manufacturer2;
    private javax.swing.JTextField manufacturingYear2;
    private javax.swing.JTextField model2;
    private javax.swing.JTextField name2;
    private javax.swing.JTextField seats2;
    private javax.swing.JTextField serial2;
    private javax.swing.JTable tblCar;
    private javax.swing.JLabel updateRefresh;
    private javax.swing.JLabel updateStatus;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblCar.getModel();
        model.setRowCount(0);
        
        for(Car car: history.getHistory()){
            Object[] row = new Object[6];
            row[0] = car;
            row[1] = car.getManufacturer();
            row[2] = car.getCity();
            row[3] = car.getNumberPlate();
            row[4] = car.isAvailability();
            row[5] = car.getDateT();
    
            model.addRow(row);
            
        }
        
    }
    
     public void refreshTable() {

        DefaultTableModel model = (DefaultTableModel) tblCar.getModel();
        model.setRowCount(0);

       for(Car car: history.getHistory()){
            Object[] row = new Object[6];
            row[0] = car;
            row[1] = car.getManufacturer();
            row[2] = car.getCity();
            row[3] = car.getNumberPlate();
            row[4] = car.isAvailability();
            row[5] = car.getDateT();
            model.addRow(row);
            
        }
       
        
}

}
